""" added relationships to budget categories and transactions

Revision ID: 1a087384685f
Revises: 59cd5ba3607d
Create Date: 2024-03-17 20:34:19.015539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a087384685f'
down_revision = '59cd5ba3607d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_categories_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_categories_budget_id_budgets'), 'budgets', ['budget_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_budget_id_budgets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_categories_transaction_id_transactions'), type_='foreignkey')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('budget_id')

    # ### end Alembic commands ###
