"""created association table to have many to many relationship with transactions and categories

Revision ID: 3d59796bb1e5
Revises: 20dc7ce3d5e7
Create Date: 2024-03-28 02:37:52.892878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d59796bb1e5'
down_revision = '20dc7ce3d5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_transaction_association',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_transaction_association_category_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_category_transaction_association_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('category_id', 'transaction_id', name=op.f('pk_category_transaction_association'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_transaction_id_transactions', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_categories_transaction_id_transactions', 'transactions', ['transaction_id'], ['id'])

    op.drop_table('category_transaction_association')
    # ### end Alembic commands ###
