"""added relationships

Revision ID: 59cd5ba3607d
Revises: 720bd8119f35
Create Date: 2024-03-06 23:20:48.838421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cd5ba3607d'
down_revision = '720bd8119f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_budgets')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_budgets_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_budgets_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_budgets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_budgets_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_budgets')
    )
    # ### end Alembic commands ###
