"""added nullable to percentage

Revision ID: 95cb6a5cfd43
Revises: 2cbf2414cf82
Create Date: 2024-03-25 10:31:14.032217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cb6a5cfd43'
down_revision = '2cbf2414cf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('percentage',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('percentage',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
