""" updated tables

Revision ID: c42ee2fef454
Revises: 3d59796bb1e5
Create Date: 2024-04-14 22:12:43.968178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42ee2fef454'
down_revision = '3d59796bb1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budgets_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_budgets_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
